### ISSUE TITLE
Migrate old knoboo issues from original trac

### ISSUE THREAD

**Issue by deldotdr** [codenode/codenode#1]
See if somebody created a migration tool.

Filter tickets; re-open appropriate ones here

**Comment by clemesha** [comment]
I just went through all the tickets here: http://trac.knoboo.com/report/1 and added all the ones that I thought are still relevant. Dorian, can you go through the list and add any others, and then close this ticket.

**Comment by deldotdr** [comment]
Done. Think I transferred relevant defects/enhancements and ideas.
