### ISSUE TITLE
Revisioned notebooks and cells

### ISSUE THREAD

**Issue by clemesha** [codenode/codenode#10]
Notebooks and their corresponding cells must have revisions. The central motivator for this is for **auto-save** functionality, you must have revisions else an _auto-save_ action might delete a bunch of code not intended to be deleted.

**Comment by clemesha** [comment]
The beginning work on this started reviewing this article:
http://lethain.com/entry/2008/oct/15/setting-up-django-rcsfield/

which quickly led to this:
http://code.djangoproject.com/wiki/AuditTrail

**Comment by codenode** [comment]
Code in commit df0c662893b1a138e198fff876ee45beab446a29 implements both revisioning of notebooks and cell, and gives the ability to do reverts.
