### ISSUE TITLE
Make plotting work again

### ISSUE THREAD

**Issue by clemesha** [codenode/codenode#11]
The refactoring for new way of running codenode (via "codenode-admin") has made it so plotting
is broken.  Plugging plotting back in should be fairly easily, and needs to be done soon.

**Comment by jamescasbon** [comment]
I notice there is the mmaptlotlib module.  Is this what you are referring to?

Is it possible to use native matplotlib?

**Comment by clemesha** [comment]
The _mmaplotlib_ is a wrapper around matplotlib, as it serves to simplifying the going from matplotlib objects to png files for the browser, among a couple other things.

With a little bit of re-working of the existing code, it will be possible to use native matplotlib.  This is in fact better that using the _mmaplotlib_ module. 

James, if you are motivated to help with the re-working to make plotting work again, that would be a great place to start to learn the inner workings of codenode, and it would be a great help to us!  Bringing this topic up on this mailing list would be great, then we can chat about the details. Thanks!

**Comment by clemesha** [comment]
Basic plotting works, but new ideas for dealing with anything that is _not_ output text are being discussed and will become new issues.
