### ISSUE TITLE
Give notebooks a human readable URL

### ISSUE THREAD

**Issue by jamescasbon** [codenode/codenode#12]
It would be very nice if notebook URLs were less: 
/notebook/2a151ef6d7154940be964cf329f7afc2/
and more:
/notebook/username/my_notebook_name

This should be possible using a django url handler that does a lookup on the notebook and redirects to the real url.

**Comment by clemesha** [comment]
I'm all for this, but the first thing that comes to mind is what about the fact that you won't even be able to have 2 notebooks with the same name.

For example, "Untitled" is the default title, and having 2 urls "/notebook/username/Untitled" won't work.

Glancing at things like Google Docs or Gmail's unique emails, they all have unique (human unreadable) urls, and this was basically the model I followed.  That said, I very much like the idea of supporting human readable urls in some way.  What type of details do you think would go into implementing this?

**Comment by jamescasbon** [comment]
No, you would not be able to have two notebooks of the same name.  I don't see this as a problem.

I have implemented this on this branch: 
http://github.com/jamescasbon/codenode/tree/issue-12

All that was needed was to add another url pattern to be handled by frontend.notebook.views.notebook.  This method will now redirect to the guid based url if it is supplied with a username and notebook title.

I also put the human url on the share form a url for sharing.  This currently doesn't have the domain name, but the url tag doesn't do this (see http://www.djangosnippets.org/snippets/1518/).  I would like to be able to share with everyone and just send them a URL.

**Comment by clemesha** [comment]
Looking closer at your solution, I really like this.  

I think what I was originally hung up on was the notion that we would do away with the guids and just having the titles be the unique identifier (and I was in fact wrong about this).  Instead what you've done is given the _ability_ to provide a human-readable url (which in turn redirects to the guid), and I think this is great!

A couple things I noticed:
- Putting a "-" in the title is not handled correctly.  This seems like an easy fix.
- If you have 2 of the same titles, like "Untitled", it just redirects to the first, which is basically fine with me for now, and thoughts on this?

Besides the above small notes, would you like this branch merged into the master soon? No hurry, but ready when you are. Thanks!

**Comment by deldotdr** [comment]
I think the model that makes most sense is to make the human readable "share" url an explicit relation (and therefore a table). The "share" relation can be thought of as a symbolic link; a human readable name for the unique guid of a users notebook. In practice, if the owner of a notebook wants to share a notebook (as a url), they would create a shared url link (in the share table) of whatever name they want, most sensibly defaulting to the url-encoded notebook Title, with a possible disambiguating integer appended to the end. The link name must be unique, but only in the owners table of shared links. This model removes the requirement of redundantly worrying about the uniqueness of notebook titles and notebook guids when sharing a notebook as a human readable url.

**Comment by clemesha** [comment]
James, please go ahead with this patch as is - I'd like to put it into codenode master, if you're still behind it.

 I think the discussion on the mailing list was good in that we talked about some of the possible issues, but I think the essence of this patch just _adds_ some cool functionality, but keeps the original guid-based access intact - something that is not going away at this time.  We appreciate your work on this!

**Comment by jamescasbon** [comment]
I am trying to work out how to deal with urls that need to be escaped.  Django's url template tag doesn't seem to be doing this.  Until this is fixed, I don't think it should be merged as it will fail too often.

**Comment by jamescasbon** [comment]
Ok that is fixed.  Now all that is needed is to get the domain name included in the share url.  But I think it is in a suitable state to merge.

**Comment by clemesha** [comment]
Great, I just merged this into codenode core.  Thanks!

**Comment by jamescasbon** [comment]
Regarding deldotdr's comments about redirects being stored in the database, see: 
http://docs.djangoproject.com/en/dev/ref/contrib/redirects/
