### ISSUE TITLE
Add in unit tests

### ISSUE THREAD

**Issue by jamescasbon** [codenode/codenode#13]
I think it is well worth having a test suite.

I have added the necessary incantations to use nose as a test runner (disclaimer: I'm on the nose dev team) on this branch: http://github.com/jamescasbon/codenode/tree/unittests

You can kick off the tests by 'python setup.py nosetests' (added this to the readme), and with a virtualenv, installing nose should be easy with pip/easy_install.

I added tests for the notebook model, and in the process improved the last_modified lookups to use self.cell_set to traverse the foreign key relationship from cells.

**Comment by clemesha** [comment]
Wow, a big thank you for starting this effort!!  The lack of unit tests is the (soon to be _was_ :) the biggest **glaring** missing feature of codenode. Having a test suite is very worth it, and this initial push will certainly motivate us to get on the ball.
