### ISSUE TITLE
Unsaved Data Warning: e.g. Hitting 'backspace' can make you leave page

### ISSUE THREAD

**Issue by clemesha** [codenode/codenode#15]
Hitting 'backspace' can make you leave the page. First off, this should not happen, and secondly if you do leave the page and there are unsaved changes, _a warning should be given_. Additionally we need to given a message that the page has saved after each action.

**Comment by clemesha** [comment]
This featured is deemed very important and in favor of having "auto-save" functionality.

**Comment by jamescasbon** [comment]
Auto save works on evaluation, we can add this easily enough: 

// Ask the user before 
$(window).bind('beforeunload', function() {
    if (Notebook.unsavedChanges) {
        return 'Are you sure you want to leave?   You have unsaved changes.';
    }
});

To prevent losing data (need to implement Notebook.unsavedChanges)

Also, do we want to intercept chrome's backspace=back functionality?

**Comment by jamescasbon** [comment]
Add Notebook.Save.hasUnsavedChanges and call window.onbeforeunload to prevent lost data. Closed by ecc97b2d2b9f7d927439bdcb62dfc20191e25525
