### ISSUE TITLE
Allow run on different port

### ISSUE THREAD

**Issue by ssteinerx** [codenode/codenode#36]
I'm currently running another Django app on the default port and would like to be able to run codenode on another port but there doesn't seem to be a switch...

**Comment by clemesha** [comment]
The way to run from a different port is to edit the "APP_PORT" settings option in the file "frontend/settings.py" in the directory that is create when you did "codenode-admin init -name mycodenode".

Possibly a better way better way is for someone to improve this function:
http://github.com/codenode/codenode/blob/master/codenode/management/commands.py#L50 to allow the passing of the frontend port.

I'm going to close this issue, as there is a way to change ports currently. Maybe it should be re-open if someone decided to pass the port as a command line option.
