### ISSUE TITLE
Revision History link causes error with unsave notebook

### ISSUE THREAD

**Issue by rpwagner** [codenode/codenode#38]
When you first create a notebook, if you click the revision history link, you get an error when trying to pop an item from an empty list of revisions. Maybe the link should be disabled until there are some revisions.

This was found using live.codenode.org on Dec. 5th.

/home/codenode/live/_cndeps2/src/codenode/codenode/frontend/notebook/revision_utils.py in get_unique_revisions
1. current_audit_id, current_audit_ts, current = revisions.pop(0)

**Comment by jamescasbon** [comment]
I get bug #44 with this, need to check after #44 is fixed.

**Comment by jamescasbon** [comment]
handle empty revision lists in get_unique_revisions.  Closed by 070a1a47b015d23bc44435c3b4f69854e198fea6
