### ISSUE TITLE
Revision history is not working

### ISSUE THREAD

**Issue by btel** [codenode/codenode#44]
When I click revision history the "'AuditTrailManager' object has no attribute '_db'" error is thrown.

**Comment by jamescasbon** [comment]
Confirmed.  See also #38

**Comment by jamescasbon** [comment]
Looks like this is broken: http://code.djangoproject.com/wiki/AuditTrail

**Comment by jamescasbon** [comment]
From http://stackoverflow.com/questions/818823/django-audittrail-vs-reversion
"""
I assume by AuditTrail you mean AuditTrail on the Django wiki. If so, I think you'll want to instead look at HistoricalRecords  developed by the same author (Marty Alchin aka @gulopine) in his book Pro Django. It should work better with Django 1.x.
""" 

Doesn't look good for AuditTrail

**Comment by jamescasbon** [comment]
updated AuditTrail. Closed by bf9abd15dfcab12d164560f25909a01f8c145494
