### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by btel** [codenode/codenode#47]
Some of the examples and commands in the documentation are not working.  Specifically the following chapters should be updated:
- Commands For Running and Managing Codenode
- Developing Codenode

**Comment by jamescasbon** [comment]
Yes, what would you like to see in developing codenode?

**Comment by btel** [comment]
Basic information on how to debug backend and frontend would be very useful. For example, how to introspect the internal variables, and messages sent between frontend and backend or how to reload the code after making changes.

**Comment by jamescasbon** [comment]
This seems closed??? How can I reopen.
