### ISSUE TITLE
Delete Cells

### ISSUE THREAD

**Issue by clemesha** [codenode/codenode#5]
There needs to be a simple way to delete cells.  This is almost implemented, but not working.

Could think about not _completely deleting_ to preserve notebook revision history

**Comment by jamescasbon** [comment]
From a UI perspective, I would like to be able to press delete at the beginning of a cell to delete it.

**Comment by clemesha** [comment]
I'm assuming you mean that if the cell is completely empty, and you hit one more delete, it deletes the cell.  This is basically the "Sage style" of doing it, and I totally agree that this needs to be supported.  Dorian posted an example of how to extend the JavaScript event handlers in the thread "Support Sage Style", and I intend to do just this unless someone beats me to it.

**Comment by clemesha** [comment]
The feature of "pressing delete at the beginning of a cell to delete it." will be coming from here: http://github.com/deldotdr/codenode/tree/keyconfig

**Comment by jamescasbon** [comment]
Delete cells.  Closed by 7aabf851d197b250adb2751b762332e40844cc44

Delete is working, and I have added the following: 
- deleting a cell calls saves the notebook
- select a bracket and press backspace deletes a cell  (helps macs who have no obvious delete)
- Context menu delete

**Comment by jamescasbon** [comment]
Reopening new ticket for backspace at start of cell
